name: flutter_video_feed_list
description: "可重复使用的垂直短视频源，具有预加载和缓存功能。"
version: 0.0.2
homepage:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.10.1
  flutter_cache_manager: ^3.4.1
  preload_page_view: ^0.2.0
  extended_image: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
